stages:
  build_dataset:
    cmd: python -m rte_mlops_demo.build_dataset rte_mlops_demo/parser_config.yaml
    params:
    - build_dataset.end_date
    - build_dataset.start_date
    outs:
    - data/raw_dataset.csv
    deps:
      - rte_mlops_demo/scraper.py
      - rte_mlops_demo/build_dataset.py
  train:
    cmd: python -m rte_mlops_demo.train
    metrics:
    - metrics.yaml:
        cache: false
    deps:
    - rte_mlops_demo/metrics.py
    - rte_mlops_demo/train.py
